objects/Contract.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <label>Total: One Time Charges</label>
        <summarizedField>vlocity_cmt__ContractLineItem__c.vlocity_cmt__OneTimeTotal__c</summarizedField>
        <summaryForeignKey>vlocity_cmt__ContractLineItem__c.vlocity_cmt__ContractId__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__ContractLineItem__c.object
<CustomObject>
    <description>Represents the product and services covered by a contract.</description>
    <fields>
        <fullName>vlocity_cmt__ContractId__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>ContractLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LineStatus__c</fullName>
        <description>Status of this Contract Line Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <description>Final total after all pricing and * Quantity</description>
        <label>One Time Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Quantity__c</fullName>
        <description>Product Quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Line</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractCustomClassTest.cls
@isTest
private with sharing class ContractCustomClassTest {
	private static testMethod void testCustomClass(){
		Account acct = new Account(name='Test');
		insert acct;
		
		Contract cont = new Contract (name='Test',AccountId=acct.Id);
		insert cont;
		
		vlocity_cmt__ContractLineItem__c line1 = new vlocity_cmt__ContractLineItem__c(Name='line1', vlocity_cmt__LineStatus__c='Active', vlocity_cmt__Quantity__c=1, vlocity_cmt__OneTimeTotal__c=1000, vlocity_cmt__ContractId__c=cont.Id);
		vlocity_cmt__ContractLineItem__c line2 = new vlocity_cmt__ContractLineItem__c(Name='line2', vlocity_cmt__LineStatus__c='Active', vlocity_cmt__Quantity__c=1, vlocity_cmt__OneTimeTotal__c=2000, vlocity_cmt__ContractId__c=cont.Id);
		vlocity_cmt__ContractLineItem__c line3 = new vlocity_cmt__ContractLineItem__c(Name='line3', vlocity_cmt__LineStatus__c='Inactive', vlocity_cmt__Quantity__c=1, vlocity_cmt__OneTimeTotal__c=3000, vlocity_cmt__ContractId__c=cont.Id);
		vlocity_cmt__ContractLineItem__c line4 = new vlocity_cmt__ContractLineItem__c(Name='line4', vlocity_cmt__LineStatus__c='Inactive', vlocity_cmt__Quantity__c=1, vlocity_cmt__OneTimeTotal__c=3000, vlocity_cmt__ContractId__c=cont.Id);
		
		List<vlocity_cmt__ContractLineItem__c> lineList = new List<vlocity_cmt__ContractLineItem__c> ();
		lineList.add(line1);
		lineList.add(line2);
		lineList.add(line3);
		lineList.add(line4);
		insert lineList;
		
		Test.startTest();
		String className='ContractCustomDocumentSectionExample';
		Type classType = Type.forName(className);
        //if classType is null, check if the class exists or not and what is the nameSpaceprefix
        if(classType == null){
     	  String customNameSpacePrefix;
     	  List<ApexClass> classList = [SELECT Name, NameSpacePrefix FROM ApexClass WHERE Name=:className LIMIT 1];
          if(classList.size() > 0){                   
		     customNameSpacePrefix = classList[0].NameSpacePrefix;
		     System.debug('class found, name space is '+customNameSpacePrefix);
		     if(customNameSpacePrefix == null || customNameSpacePrefix.equals('')){
		         customNameSpacePrefix = '';
		     }
		     classType=Type.forName(customNameSpacePrefix, className);
     	  } 
       }
       if(classType !=null){
          Map<String, Object> inputMap = new Map<String, Object> ();
          Map<String, Object> outputMap = new Map<String, Object> ();
          Map<String, Object> options = new Map<String, Object> ();
          vlocity_cmt.VlocityOpenInterface vpsi = (vlocity_cmt.VlocityOpenInterface)classType.newInstance();  
          inputMap.put('contextObjName', 'Contract');          
          inputMap.put('contextObjId', cont.Id); 
          inputMap.put('items', lineList);
          inputMap.put('documentFontStyle', 'Aria, times, serif');
          vpsi.invokeMethod('buildDocumentSectionContent',inputMap, outputMap, options);
          String sectionContent = (String) outputMap.get('sectionContent');
          
          System.assertNotEquals(sectionContent, null);
       }		
       
       Test.stopTest();
	
	}

}