objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__RecurringPrice__c</fullName>
        <label>Recurring Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubType__c</fullName>
        <description>Product Sub Type can be used to drive implementations/engines, as well as filtering products in the Catalog/Pricebook. These values may be constrained by the Product Type.</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Electricity</fullName>
                </value>
                <value>
                    <fullName>Unit Rate</fullName>
                </value>
                <value>
                    <fullName>Standing Charges</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Commodity</fullName>
                </value>
                <value>
                    <fullName>Cost Component</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SampleDefaultAvailabilityImplementation.cls
global with sharing class SampleDefaultAvailabilityImplementation implements vlocity_cmt.GlobalInterfaces.ProductAvailabilityInterface{

	public List<PriceBookEntry> getAvailableProducts(SObject parentItem, List<PriceBookEntry> pbeList){
		if(pbeList ==null || (pbeList !=null && pbeList.size()==0)) {     
       		pbeList = new List<PriceBookEntry> ();
	        try{
		        Id itemId = (Id)parentItem.get('Pricebook2Id');
		        pbeList = [Select Id
		                         ,Pricebook2Id
		                         ,Product2Id
		                         ,ProductCode
		                         ,Product2.vlocity_cmt__Type__c
		                         ,Product2.vlocity_cmt__SubType__c
		                         ,Product2.Description
		                         ,UnitPrice
		                         ,Name
		                         ,Product2.Name
		                         ,Product2.vlocity_cmt__JSONAttribute__c
		                         ,vlocity_cmt__RecurringPrice__c
		                         ,IsActive 
		                        from PricebookEntry
		                        where Pricebook2Id = :itemId 
		                        	AND (Product2.recordTypeId = null OR Product2.recordType.DeveloperName = 'Product')];
	        }catch(Exception e){
	        	throw e;
	        }
       }
       
       system.debug(':::Executed SampleDefaultAvailabilityImplementation');	
       return pbeList;
		
	}
}