objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__RecurringPrice__c</fullName>
        <label>Recurring Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubType__c</fullName>
        <description>Product Sub Type can be used to drive implementations/engines, as well as filtering products in the Catalog/Pricebook. These values may be constrained by the Product Type.</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Electricity</fullName>
                </value>
                <value>
                    <fullName>Unit Rate</fullName>
                </value>
                <value>
                    <fullName>Standing Charges</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Commodity</fullName>
                </value>
                <value>
                    <fullName>Cost Component</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing Customer - Upgrade</fullName>
                </value>
                <value>
                    <fullName>Existing Customer - Replacement</fullName>
                </value>
                <value>
                    <fullName>Existing Customer - Downgrade</fullName>
                </value>
                <value>
                    <fullName>New Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__ProductAvailability__c.object
<CustomObject>
    <description>Individual products and services may not be available in all geographical areas. For example, selected channels may not be authorized to broadcast within a given state or locale. Or a given telecommunications product may simply not yet be available in a given region. To accommodate such exclusions, &quot;rules&quot; regarding product availability can be defined. If a product is denoted as unavailable within a select state or zip code range, that product will not be suggested when creating a new order, opportunity, or quote, where the shipping address is in that state or zip code range.</description>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products Not Available</relationshipLabel>
        <relationshipName>ProductEligibility</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Not Available</label>
    <nameField>
        <label>Product Not Available Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Not Available</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SampleAvailabilityImplementation.cls
global with sharing class SampleAvailabilityImplementation implements vlocity_cmt.GlobalInterfaces.ProductAvailabilityInterface{

    public List<PriceBookEntry> getAvailableProducts(SObject parentItem, List<PriceBookEntry> pricebookEntryList){
    /*
    *  Normally Availability runs before Eligibility
    *  This sample runs Eligibility first, then Availability
    */
        String nsp = 'vlocity_cmt__';
  
        // run the Eligibility that is set up
        String productElig = 'SampleDefaultEligibilityImplementation';//CustomSettingsUtilities.getCustomClassImplemenationName('ProductEligibility');
        Type et = Type.forName(productElig); 
        vlocity_cmt.GlobalInterfaces.ProductEligibilityInterface pei = (vlocity_cmt.GlobalInterfaces.ProductEligibilityInterface)et.newInstance();
        pricebookEntryList = pei.getEligibleProducts(parentItem, pricebookEntryList);
             
        //now run the specific Availability that you want - here 'Default...'  
        // have to specify the implementation since this file presumeably overrides it     
        String impl = 'vlocity_cmt.LocaleProductAvailability';
        Type t = Type.forName(impl);    
        vlocity_cmt.GlobalInterfaces.ProductAvailabilityInterface pai = (vlocity_cmt.GlobalInterfaces.ProductAvailabilityInterface)t.newInstance();
        pricebookEntryList = pai.getAvailableProducts(parentItem,pricebookEntryList);
        
        //this logic excludes products based on Order(Quote).ShippingCity which compares to
        //record in ProductAvailability__c object where City__c can be set
    /*
    *	To run this code for an Oppty you will have to create a formula field for ShippingCity
    *   In Opportunity add field: ShippingCity__c as formula: Account.ShippingCity
    */
    	String shipCityQry;
    	String objectName = String.valueOf(parentItem.getSObjectType());
        if(objectName == 'Opportunity') {
        // without adding the field to Opportunity this won't work, but it shouldn't fail since it's just setting up 
        // the query string
        	shipCityQry ='ShippingCity__c';
        }
        else {
       		shipCityQry ='ShippingCity'; 
        }
        String shipCity = (String)parentItem.get(shipCityQry);
       	String pricebkId = (String)parentItem.get('Pricebook2Id');
       	
       	Map<ID, String> productIdMap = new Map<ID, String> ();
        for(PriceBookEntry pbe: pricebookEntryList){
           productIdMap.put(pbe.Product2Id, 'ProductId');
        }
        List<vlocity_cmt__ProductAvailability__c> ruleList  = [SELECT ID, vlocity_cmt__City__c, vlocity_cmt__Product2Id__c From vlocity_cmt__ProductAvailability__c 
        	WHERE vlocity_cmt__Product2Id__c IN :productIdMap.keySet()  AND vlocity_cmt__City__c != null];
		for(vlocity_cmt__ProductAvailability__c pat: ruleList){  

			 if(pat.vlocity_cmt__City__c == shipCity){
                  productIdMap.remove(pat.vlocity_cmt__Product2Id__c); 
             }
		}  
		if(productIdMap !=null){
             pricebookEntryList = [SELECT Id,Pricebook2Id,Product2Id,Product2.vlocity_cmt__Type__c,Product2.vlocity_cmt__SubType__c,ProductCode,
             		Product2.Description,Product2.Name,UnitPrice,Name,Product2.vlocity_cmt__JSONAttribute__c,vlocity_cmt__RecurringPrice__c,IsActive
                    FROM PricebookEntry 
                    WHERE Pricebook2Id = :pricebkId AND IsActive=true AND Product2Id IN :productIdMap.keySet() Order by Product2.Name];
		}             
        
        system.debug(':::Executed SampleAvailabilityImplementation');
        
        return pricebookEntryList;
    }
     
}