objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__RecurringPrice__c</fullName>
        <label>Recurring Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubType__c</fullName>
        <description>Product Sub Type can be used to drive implementations/engines, as well as filtering products in the Catalog/Pricebook. These values may be constrained by the Product Type.</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Electricity</fullName>
                </value>
                <value>
                    <fullName>Unit Rate</fullName>
                </value>
                <value>
                    <fullName>Standing Charges</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Commodity</fullName>
                </value>
                <value>
                    <fullName>Cost Component</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__ProductEligibility__c.object
<CustomObject>
    <description>This object provides the option for products to be denoted as ineligible under certain circumstances. For example, a product may not be eligible for an account unless that account is a business account with a Gold level SLA (Service Level Agreement). Such exceptions are defined within this object.</description>
    <fields>
        <fullName>vlocity_cmt__AnnualRevenue__c</fullName>
        <label>Annual Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>ProductEligibilityProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Not Eligible</label>
    <nameField>
        <label>Product Not Eligible Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Not Eligible</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SampleEligibilityImplementation.cls
global with sharing class SampleEligibilityImplementation implements vlocity_cmt.GlobalInterfaces.ProductEligibilityInterface{
	
	public List<PricebookEntry> getEligibleProducts (SObject parentItem, List<PriceBookEntry> pricebookEntryList) {
/* 
*  This code runs the AccountTypeProductEligibility (our original code)
*  It then further limits that result set based on Annual Revenue.  
*		Account.AnnualRevenue is a std field
*       ProductChildItem__c.AnnualRevenue__c is a telco field that has been there since the beginning but not
*          exposed in the layout.  The logic below excludes the product if the PCI.AnnualRevenue > Account.AnnualRevenue
*/		
		// run the  Vloc Eligibility 
		String impl = 'vlocity_cmt.AccountTypeProductEligibility';
        Type et = Type.forName(impl);
        vlocity_cmt.GlobalInterfaces.ProductEligibilityInterface pei = (vlocity_cmt.GlobalInterfaces.ProductEligibilityInterface)et.newInstance();
        pricebookEntryList = pei.getEligibleProducts(parentItem, pricebookEntryList);

        // now exclude products for accounts with < specified Annual Revenue
        String pricebkId = (String)parentItem.get('Pricebook2Id');
       	ID recordId = (ID)parentItem.get('AccountId'); 
       	
        Map<ID, String> productIdMap = new Map<ID, String> ();
        for(PriceBookEntry pbe: pricebookEntryList){
           productIdMap.put(pbe.Product2Id, 'ProductId');
        }
        
        Schema.SObjectType objType =  parentItem.getSObjectType();  
        String objName = objType.getDescribe().getName();
        Account acct = [SELECT ID, AnnualRevenue FROM Account WHERE ID =:recordId LIMIT 1];
        Double annRevenue = acct.AnnualRevenue;
       
        List<vlocity_cmt__ProductEligibility__c> ruleList  = [SELECT ID, vlocity_cmt__AnnualRevenue__c, vlocity_cmt__Product2Id__c From vlocity_cmt__ProductEligibility__c 
        	WHERE vlocity_cmt__Product2Id__c IN :productIdMap.keySet()  AND vlocity_cmt__AnnualRevenue__c != null];
		for(vlocity_cmt__ProductEligibility__c pet: ruleList){  

			 if(pet.vlocity_cmt__AnnualRevenue__c > annRevenue){
                  productIdMap.remove(pet.vlocity_cmt__Product2Id__c);
             }
		}  
		if(productIdMap !=null){
             pricebookEntryList = [SELECT Id,Pricebook2Id,Product2Id,Product2.vlocity_cmt__Type__c,Product2.vlocity_cmt__SubType__c,ProductCode,
             		Product2.Description,Product2.Name,UnitPrice,Name,Product2.vlocity_cmt__JSONAttribute__c,vlocity_cmt__RecurringPrice__c,IsActive
                    FROM PricebookEntry 
                    WHERE Pricebook2Id = :pricebkId AND IsActive=true AND Product2Id IN :productIdMap.keySet() Order by Product2.Name];
		}             
    
        system.debug(':::Executed Sample Eligibility Implementation');
        
        return pricebookEntryList;
	}
}