objects/vlocity_cmt__Datastore__c.object
<CustomObject>
    <description>Vlocity Data store to be used as persistent cache.</description>
    <fields>
        <fullName>vlocity_cmt__Key__c</fullName>
        <description>The full key field (up to 255 characters) which fully identifies this entry in the data store.</description>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies a product when this entry is related to a specific product.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Data Store Item</relationshipLabel>
        <relationshipName>DataStoreItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Value__c</fullName>
        <description>The long text value of the data store entry.</description>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Vlocity Data Store</label>
    <nameField>
        <label>VlocityDataStore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Data Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__ProductChildItem__c.object
<CustomObject>
    <description>Product Child Items define the component products associated with a grouped package of products or services. Sometimes products are grouped to accommodate specialized pricing. The child items are automatically added to the cart when the parent product is added, so child items are always created when products are sold together. May represent the make up of product offerings, product specifications, resources specifications or service specifications.</description>
    <fields>
        <fullName>vlocity_cmt__ChildProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Child Items (Child)</relationshipLabel>
        <relationshipName>ProductChildItemsChild</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsOverride__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsRootProductChildItem__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to identify the root product child item record.
Only one will be allowed for each root product.</description>
        <label>Is Root Product Child Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ParentProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Child Items</relationshipLabel>
        <relationshipName>ProductChildItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Child Item</label>
    <nameField>
        <label>Product Child Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Child Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UMResolveProductHierarchyBatchJob.cls
/*
 TO RUN THIS batch job FROM ANONYMOUS MODE  paste this code :


 String query = ' SELECT ParentProductId__c , ';
        query         += '         ChildProductId__c ';
        query        += ' FROM     ProductChildItem__c WHERE IsRootProductChildItem__c = false AND IsOverride__c = false';
        query        += '  AND ParentProductId__c != NULL AND ChildProductId__c != NULL';
        UMResolveProductHierarchyBatchJob resolveProductHierarchy = new UMResolveProductHierarchyBatchJob(query, '',true, 0);
        Database.executeBatch(resolveProductHierarchy,2000);

*/

public with sharing class UMResolveProductHierarchyBatchJob implements Database.Batchable<sObject>, Database.Stateful {
	public final String installerEmail;
	public Id jobId;
	public Boolean needsAnotherPass;
	public final String query;
	public final Id recordTypeId;
	public Integer passesCount;
	
	public UMResolveProductHierarchyBatchJob(String query, String installerEmail, Boolean removeOldRecords, Integer passesCount){
		
		this.recordTypeId = Schema.SObjectType.vlocity_cmt__DataStore__c.getRecordTypeInfosByName().get('Product Hierarchy').getRecordTypeId();
		this.query = query;
		this.installerEmail = installerEmail;	
		this.needsAnotherPass = false;	
		this.passesCount = passesCount;
		//delete old values
		if(removeOldRecords){
			delete[SELECT Id FROM vlocity_cmt__DataStore__c WHERE RecordTypeId =: recordTypeId];
			
		}
		
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC){
		this.jobId = BC.getJobId();
		return Database.getQueryLocator(query);
		
	}
	
	public void execute(Database.BatchableContext BC, List<sObject> scope){
		resolveProductHierearchyItems(BC, scope);
		
	}
	
	public void finish(Database.BatchableContext BC){
		if(passesCount < 20 && needsAnotherPass){
			passesCount++;
			//start another batch to resolve any missing items
			String query = ' SELECT vlocity_cmt__ParentProductId__c , ';
			query 		+= ' 		vlocity_cmt__ChildProductId__c ';
			query		+= ' FROM 	vlocity_cmt__ProductChildItem__c WHERE vlocity_cmt__IsRootProductChildItem__c = false AND vlocity_cmt__IsOverride__c = false';
			query		+= '  AND vlocity_cmt__ParentProductId__c != NULL AND vlocity_cmt__ChildProductId__c != NULL';
			UMResolveProductHierarchyBatchJob resolveProductHierarchy = new UMResolveProductHierarchyBatchJob(query, '', false, passesCount);
			Database.executeBatch(resolveProductHierarchy, 2000);
			

		} else {
			AsyncApexJob job = [SELECT Id, 
									   Status, 
									   NumberOfErrors, 
									   JobItemsProcessed, 
									   TotalJobItems,
									   CreatedBy.Email
							    FROM AsyncApexJob 
							    WHERE Id = :bc.getJobId()];
			// send status email to user's email
			String userEmail = String.isNotBlank(installerEmail)?installerEmail:Job.CreatedBy.Email;
			if (String.isNotBlank(userEmail)) {			
				Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
				String[] toAddresses = new String[] {userEmail};
				mail.setToAddresses(toAddresses);
				mail.setSubject('Vlocity Product Hierarchy Batch Job  (' + bc.getJobId() + ') ' + job.Status);
				mail.setPlainTextBody('The batch Apex job processed ' + job.TotalJobItems +
									  ' batches with ' + job.NumberOfErrors + ' failures.');
				Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });	
			}
		
		}
		
	}
	
	// bind attribute values to sobject fields
	public void resolveProductHierearchyItems(Database.BatchableContext BC, List<sObject> scope){
        		/********************* SAMPLE CODE  DELETE THE COMMENT TO ACTIVATE THIS CODE ********************

		Map<Id, List<vlocity_cmt__ProductChildItem__c>> childProductIdToPciList = new Map<Id, List<vlocity_cmt__ProductChildItem__c>>();
		Set<Id> productIds = new Set<Id>();
		for(sObject item : scope){
			vlocity_cmt__ProductChildItem__c pci = (vlocity_cmt__ProductChildItem__c) item;
			productIds.add(pci.vlocity_cmt__ParentProductId__c);
			productIds.add(pci.vlocity_cmt__ChildProductId__c);
			if(childProductIdToPciList.get(pci.vlocity_cmt__ChildProductId__c) == null){
				childProductIdToPciList.put(pci.vlocity_cmt__ChildProductId__c,new List<vlocity_cmt__ProductChildItem__c>());
				
			}
			
			childProductIdToPciList.get(pci.vlocity_cmt__ChildProductId__c).add(pci);
			
		}
		
		Map<Id, vlocity_cmt__DataStore__c> productIdToPhiMap = new Map<Id, vlocity_cmt__DataStore__c>();
		Map<Id, Set<String>> contextProductIdToPciIds = new Map<Id, Set<String>>();
		for(vlocity_cmt__DataStore__c phi :[SELECT vlocity_cmt__ProductId__c, vlocity_cmt__Value__c, vlocity_cmt__Key__c FROM vlocity_cmt__DataStore__c WHERE vlocity_cmt__ProductId__c IN :productIds AND RecordTypeId =: recordTypeId]){
			productIdToPhiMap.put(phi.vlocity_cmt__ProductId__c, phi);
			contextProductIdToPciIds.put(phi.vlocity_cmt__ProductId__c, new Set<String>(phi.vlocity_cmt__Value__c.split(',')));
		}
		
		//Map<Id, Set<String>> contextProductIdToPciIds = new Map<Id, Set<String>>();
		for(sObject item : scope){
			vlocity_cmt__ProductChildItem__c pci = (vlocity_cmt__ProductChildItem__c) item;
			if(productIdToPhiMap.get(pci.vlocity_cmt__ChildProductId__c) != null && productIdToPhiMap.get(pci.vlocity_cmt__ChildProductId__c).vlocity_cmt__Value__c != null){
				if(contextProductIdToPciIds.get(pci.vlocity_cmt__ChildProductId__c) == null){
					contextProductIdToPciIds.put(pci.vlocity_cmt__ChildProductId__c, new Set<String>());
				}
				
				contextProductIdToPciIds.get(pci.vlocity_cmt__ChildProductId__c).addAll(productIdToPhiMap.get(pci.vlocity_cmt__ChildProductId__c).vlocity_cmt__Value__c.split(','));
				
			}
			resolveHighestPCI(childProductIdToPciList, contextProductIdToPciIds, pci);
			
		}
		
		List<vlocity_cmt__DataStore__c> itemsToUpdate = new List<vlocity_cmt__DataStore__c>();
		
		for(Id productId : contextProductIdToPciIds.keyset()){
			vlocity_cmt__DataStore__c productphi = productIdToPhiMap.get(productId);
			Set<String> pciIds = contextProductIdToPciIds.get(productId);
			if(productphi == null){
				vlocity_cmt__DataStore__c productHierarchyItems = new vlocity_cmt__DataStore__c();
				productHierarchyItems.vlocity_cmt__ProductId__c = productId;
				productHierarchyItems.RecordTypeId = this.recordTypeId;
				productHierarchyItems.vlocity_cmt__Key__c = productId;
				List<String> pciIdsList = new List<String>(pciIds);
				productHierarchyItems.vlocity_cmt__Value__c = String.join(pciIdsList,',');
				itemsToUpdate.add(productHierarchyItems);
				needsAnotherPass = true;
			} else {
				Set<String> existingIds = new Set<String>(productphi.vlocity_cmt__Value__c.split(','));
				Set<String> newIds = pciIds;
				if(newIds.isEmpty() || newIds.equals(existingIds)){
					continue;	
					
				} else if(newIds.size() < existingIds.size() && existingIds.containsAll(newIds)){
					continue;
					
				}
				
				newIds.addAll(existingIds);
				List<String> pciIdsList = new List<String>(newIds);
				productphi.vlocity_cmt__Value__c = String.join(pciIdsList,',');
				itemsToUpdate.add(productphi);
				needsAnotherPass = true;
				
			}
			
		}
		
		upsert itemsToUpdate;
		********************* SAMPLE CODE  DELETE THE COMMENT TO ACTIVATE THIS CODE ********************/
		
	} 
	
	private void resolveHighestPCI(Map<Id, List<vlocity_cmt__ProductChildItem__c>> childProductIdToPciList, Map<Id, Set<String>> contextProductIdToPciIds, vlocity_cmt__ProductChildItem__c pci){
				/********************* SAMPLE CODE  DELETE THE COMMENT TO ACTIVATE THIS CODE ********************

		if(contextProductIdToPciIds.get(pci.vlocity_cmt__ParentProductId__c) == null){
            contextProductIdToPciIds.put(pci.vlocity_cmt__ParentProductId__c, new Set<String>());
            
        } 
        
        contextProductIdToPciIds.get(pci.vlocity_cmt__ParentProductId__c).add(pci.Id);
        if(contextProductIdToPciIds.get(pci.vlocity_cmt__ChildProductId__c) != null){
        	contextProductIdToPciIds.get(pci.vlocity_cmt__ParentProductId__c).addAll(contextProductIdToPciIds.get(pci.vlocity_cmt__ChildProductId__c));
        	
        }
            
        if(childProductIdToPciList.get(pci.vlocity_cmt__ParentProductId__c) == null){
        	if(childProductIdToPciList.get(pci.vlocity_cmt__ParentProductId__c) == null){
	            if(contextProductIdToPciIds.get(pci.vlocity_cmt__ChildProductId__c) == null)
	            return;
	            
	            if(contextProductIdToPciIds.get(pci.vlocity_cmt__ParentProductId__c) == null){
	                contextProductIdToPciIds.put(pci.vlocity_cmt__ParentProductId__c, contextProductIdToPciIds.get(pci.vlocity_cmt__ChildProductId__c));
	                
	            } else {
	                contextProductIdToPciIds.get(pci.vlocity_cmt__ParentProductId__c).addAll(contextProductIdToPciIds.get(pci.vlocity_cmt__ChildProductId__c));
	                
	            }
	                
				return;
				
	        }
	        
        }
		
		for(vlocity_cmt__ProductChildItem__c parentPCI : childProductIdToPciList.get(pci.vlocity_cmt__ParentProductId__c)){
			if(contextProductIdToPciIds.get(parentPCI.vlocity_cmt__ParentProductId__c) == null){
				contextProductIdToPciIds.put(parentPCI.vlocity_cmt__ParentProductId__c, new Set<String>());
				
			}
			
			contextProductIdToPciIds.get(parentPCI.vlocity_cmt__ParentProductId__c).add(parentPCI.Id);
			if(contextProductIdToPciIds.get(parentPCI.vlocity_cmt__ChildProductId__c) != null){
            	contextProductIdToPciIds.get(parentPCI.vlocity_cmt__ParentProductId__c).addAll(contextProductIdToPciIds.get(parentPCI.vlocity_cmt__ChildProductId__c));
            	   
            }
            
			resolveHighestPCI(childProductIdToPciList, contextProductIdToPciIds, parentPCI);
		
		}
		 ********************* SAMPLE CODE  DELETE THE COMMENT TO ACTIVATE THIS CODE ********************/

	}
}