objects/vlocity_cmt__ObjectClass__c.object
<CustomObject>
    <description>Represents an object or object type that is used to describe the capabilities of that object or object type to Vlocity services and applications. Object types are based on a parent object and can be based on parent object types forming a class hierarchy.</description>
    <fields>
        <fullName>vlocity_cmt__EffectiveFromDate__c</fullName>
        <label>Effective From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ObjectApiName__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vlocity Object or Object Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Objects and Object Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__PriceList__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CurrencyCode__c</fullName>
        <label>Currency Code</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>vlocity_cmt__CurrencyCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__EffectiveFromDate__c</fullName>
        <label>Effective From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LoyaltyCode__c</fullName>
        <label>Loyalty Code</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>vlocity_cmt__LoyaltyCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Pricebook2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PriceList</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceList</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__PricingElement__c.object
<CustomObject>
    <description>Represents the definition of a price, charge, cost, fee, tax, discount or adjustment such as a monthly recurring charge of $50. Used for integration with rating systems (billing or charging). Used to identify a specific price, charge or adjustment available from the rating system.</description>
    <fields>
        <fullName>vlocity_cmt__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CurrencyCode__c</fullName>
        <label>Currency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>vlocity_cmt__CurrencyCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__EffectiveFromDate__c</fullName>
        <label>Effective From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsReusable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reusable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LoyaltyCode__c</fullName>
        <label>Loyalty Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>vlocity_cmt__LoyaltyCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ObjectTypeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Element Object Type</label>
        <referenceTo>vlocity_cmt__ObjectClass__c</referenceTo>
        <relationshipLabel>Pricing Elements</relationshipLabel>
        <relationshipName>PricingElements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Pricing Elements</relationshipLabel>
        <relationshipName>PricingElements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PricingVariableId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Variable</label>
        <referenceTo>vlocity_cmt__PricingVariable__c</referenceTo>
        <relationshipLabel>Pricing Elements</relationshipLabel>
        <relationshipName>PricingElements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Pricing Element</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__PricingVariable__c.object
<CustomObject>
    <description>Represents a declared type of price, charge, cost, fee, tax, discount or adjustment to be used to price products or services. This is metadata that enables agile pricing definition to quickly bring new products to market.</description>
    <fields>
        <fullName>vlocity_cmt__AdjustmentMethod__c</fullName>
        <label>Adjustment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Absolute</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Aggregation__c</fullName>
        <label>Aggregation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Quantity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AppliesToVariableId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applies To Variable</label>
        <referenceTo>vlocity_cmt__PricingVariable__c</referenceTo>
        <relationshipLabel>Pricing Variables Applied</relationshipLabel>
        <relationshipName>PricingVariablesApplied</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ChargeType__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>One-time</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CurrencyType__c</fullName>
        <label>Currency Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                    <default>true</default>
                    <label>Currency</label>
                </value>
                <value>
                    <fullName>Loyalty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RecurringFrequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Scope__c</fullName>
        <label>Scope</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Line</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Parent Rollup</fullName>
                </value>
                <value>
                    <fullName>Master Rollup</fullName>
                </value>
                <value>
                    <fullName>Master</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Group Rollup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubType__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ValueType__c</fullName>
        <label>ValueType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calculated</fullName>
                </value>
                <value>
                    <fullName>Pricing Element</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Variable</label>
    <nameField>
        <label>Pricing Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EPCPEUpdateCurrencyCodeTest.cls
@isTest
private class EPCPEUpdateCurrencyCodeTest
{
    @testSetup static void setupData()
    {
        vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = Test.getStandardPricebookId(), vlocity_cmt__IsActive__c = true,
            vlocity_cmt__Code__c = 'TestPricebook', vlocity_cmt__CurrencyCode__c = 'USD', vlocity_cmt__LoyaltyCode__c = 'PTS');
        insert pl1;
        pl1 = [Select Id From vlocity_cmt__PriceList__c limit 1];

        List<String> types = new List<String>();
        types.add('vlocity_cmt__ObjectClass__c');
        List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(types);
        Map<String,Schema.RecordTypeInfo> rtMapByName = results[0].getRecordTypeInfosByName();
        Id objectRTId = rtMapByName.get('Object Type').getRecordTypeId();

        vlocity_cmt__ObjectClass__c chargeObjType = new vlocity_cmt__ObjectClass__c(Name = 'Charge', vlocity_cmt__ObjectApiName__c = 'PricingElement__c', RecordTypeId = objectRTId);
        insert chargeObjType;
        chargeObjType = [Select Id, Name from vlocity_cmt__ObjectClass__c where Name like 'Charge' limit 1];

        vlocity_cmt__PricingVariable__c pv = new vlocity_cmt__PricingVariable__c(
        Name ='One Time Std Price',
        vlocity_cmt__AdjustmentMethod__c = null,
        vlocity_cmt__Aggregation__c = 'Unit',
        vlocity_cmt__AppliesToVariableId__c = null,
        vlocity_cmt__ChargeType__c = 'One-time',
        vlocity_cmt__Code__c = 'OT_STD_PRC',
        vlocity_cmt__IsActive__c = true,
        vlocity_cmt__RecurringFrequency__c = null,
        vlocity_cmt__Scope__c = 'Line',
        vlocity_cmt__SubType__c = 'Standard',
        vlocity_cmt__Type__c = 'Price',
        vlocity_cmt__ValueType__c = 'Pricing Element',
        vlocity_cmt__CurrencyType__c = 'Currency'
        );
        insert pv;
        pv = [Select Id From vlocity_cmt__PricingVariable__c limit 1];

        vlocity_cmt__PricingElement__c pElem1 = new vlocity_cmt__PricingElement__c(Name = 'One Time $100 Standalone Price', vlocity_cmt__ObjectTypeId__c = chargeObjType.Id, vlocity_cmt__Amount__c = 100.00,
                vlocity_cmt__Code__c = 'PELEM1', vlocity_cmt__CurrencyCode__c=null, vlocity_cmt__EffectiveFromDate__c = Datetime.now(), vlocity_cmt__IsActive__c = true, vlocity_cmt__IsReusable__c = true, vlocity_cmt__PricingVariableId__c = pv.Id, vlocity_cmt__PriceListId__c = pl1.Id);
        insert pElem1;
        vlocity_cmt__PricingElement__c pElem2 = [Select Id from vlocity_cmt__PricingElement__c where vlocity_cmt__PriceListId__c != null AND vlocity_cmt__CurrencyCode__c = null];

    }

    @isTest static void testBatch()
    {
        Id batchId = Database.executeBatch(new EPCPEUpdateCurrencyCode());
        System.assertNotEquals(batchId, null);
    }
}