objects/vlocity_cmt__ContractVersion__c.object
<CustomObject>
    <description>Represents an online version of a contract document. A contract document can have physical files attached to it such as Word files or PDF files.</description>
    <fields>
        <fullName>vlocity_cmt__ContractId__c</fullName>
        <description>Contract document version</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__DocumentTemplate__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__ApplicableTypes__c</fullName>
        <description>The type of SFDC objects (headers) the Template is applicable to</description>
        <label>Applicable Objects</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denoted if the document template is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractAmendmentTest.cls
@isTest
public class ContractAmendmentTest{
   static testMethod void testCreateDocument(){  
       Account acct = new Account(Name='Test');
       insert acct;
       
       Contract newContract = new Contract(Name='Test', AccountId=acct.Id);
       insert newContract;
       vlocity_cmt__ContractVersion__c version = new vlocity_cmt__ContractVersion__c (Name='Test', vlocity_cmt__ContractId__c=newContract.Id);
       insert version;
       
       vlocity_cmt__DocumentTemplate__c docTemplate1 = new vlocity_cmt__DocumentTemplate__c();
       docTemplate1.Name = 'Test Document Template';
       docTemplate1.vlocity_cmt__IsActive__c=true;
       docTemplate1.vlocity_cmt__ApplicableTypes__c='Opportunity; Order';
       insert docTemplate1;
       
       test.startTest();
       
       Type t = Type.forName('CreateAmendmentDocument');
       vlocity_cmt.VlocityOpenInterface vpsi = (vlocity_cmt.VlocityOpenInterface)t.newInstance();
       
       Map<String, Object> inputMap = new Map<String, Object>();
       Map<String, Object> outputMap = new Map<String, Object>();
       Map<String, Object> optionsMap = new Map<String, Object>();
       
       vpsi.invokeMethod('getDocxTemplate', inputMap, outputMap, optionsMap); 
       String relsXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+
            '<Relationships '+
                'xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+
                '<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>'+
                '<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings" Target="webSettings.xml"/>'+
                '<Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes" Target="footnotes.xml"/>'+
                '<Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes" Target="endnotes.xml"/>'+
                '<Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/>'+
                '<Relationship Id="rId8" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>'+
                '<Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/>'+
                '<Relationship Id="rId10" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/>'+
                '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>'+
                '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'+
            '</Relationships>';
       inputMap.put('relXml', relsXml);
       Map<String, Object> innerMap = new Map<String, Object>();
       innerMap.put('Id', docTemplate1.Id);
       List<Object> templateList = new List<Object>();
       templateList.add(innerMap);
       Map<String, Object> docTempMap = new Map<String, Object>();
       docTempMap.put('DocumentTemplate', templateList);
       inputMap.put('PickTemplate', docTempMap);
       inputMap.put('DRId_vlocity_cmt__ContractVersion__c', version.Id);
       inputMap.put('DRId_Contract', newContract.Id);
            
       vpsi.invokeMethod('createWordDoc', inputMap, outputMap, optionsMap); 
       
       try{
           vpsi.invokeMethod('attachDocx', inputMap, outputMap, optionsMap); 
           }catch(Exception e){
           }
       
       test.stopTest();
   }
}